`StaffSection` のリファクタリング
FlutterKaigi/2023 pull request #112
Opened 2023-07-14 16:06 UTC by daiki1003

## Overview (Required)

- `iterable_ex` を追加
  - [intersperse | Dart Package](https://pub.dev/packages/intersperse)の自作みたいな感じです
- #93 の調査を行いつつ、`StaffSection` のリファクタリングを行いました

### Before 

- `StaffSection` のprivate class

### After

- `StaffSection` (その名の通りスタッフセクション全体)
  - `StaffTable` (スタッフのテーブル表示部分)
    - `StaffRow` (スタッフの一行分)
      - `StaffItem` (一つのスタッフ)

という構造になりました。

2023-07-14 17:04 UTC, YumNumm requested changes
ご対応ありがとうございます!! 
全体的に問題なさそうです! 

`StaffWidget`の横幅計算関数の実装ミスがあったので こちら修正していただけると助かります! (自分のミスです...!)

2023-07-14 17:04 UTC, YumNumm commented on lib/features/staff/ui/staff_row.dart
> +  }
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
- こちらの`16`の部分、`StaffRow.spacing`と同じかと思われますので、合わせて修正した方が良いように感じました!

ただ、コードが煩雑になってしまうような気もしつつ、こちら修正するかはおまかせします!

![must-badge](https://img.shields.io/badge/review-must-red.svg)
すみません... 自分の実装ミスです...
>     // y = 171x + 16(x - 1)
>    // y - 16 = 187x
こちら、計算ミスしておりました....

```suggestion
  // 余白を考慮しつつ 最大横に何個並べられるかを計算する
  static int calculateItemCount({
    required double maxWidth,
  }) {
    // yを最大横幅 xを横の最大要素数として、
    // y = 171x + spacing * (x - 1)
    // y + spacing = (171 + spacing) * x
    // x = (y + spacing) / (171 + spacing)
    final result = ((maxWidth - spacing) / (171 + spacing)).floor();
    return switch (result) {
      < 2 => 2,
      > 5 => 5,
      _ => result,
    };
  }

  static double calculateItemWidth({
    required double maxWidth,
  }) {
    final itemCount = calculateItemCount(maxWidth: maxWidth);
    return (maxWidth - spacing * (itemCount - 1)) / itemCount;
  }
```

2023-07-15 06:40 UTC, daiki1003 commented on lib/features/staff/ui/staff_row.dart
> +  }
修正しました！

2023-07-15 13:03 UTC, YumNumm approved these changes

2023-07-18 01:08 UTC, merged