`Spaces.horizontal` 及び `Spaces.vertical` を追加し、水平垂直方向のマージンを定数的に表現できる様に修正
FlutterKaigi/2023 pull request #113
Opened 2023-07-14 16:21 UTC by daiki1003

## Overview (Required)

- 水平垂直方向のマージンを定数的に表現できるように `Spaces` クラスを追加しました
  - 狙いとしては、マージンがマージンであることがコードを読んでわかること
    - 元々は描画範囲を設定する `SizedBox` とマージンを設定する `SizedBox` が混在していた
  - 統一感の観点で、雑多な大きさのマージンが生まれない様にすること
    - 基本的には、4の倍数で作りたい
    - こちらの観点からUIが崩れない程度に、既存の値を少しだけ変更させてもらっているところがあります

2023-07-14 17:12 UTC, YumNumm approved these changes
コードの可読性が上がりました! 対応いただきありがとうございます!
![LGTM](https://images.lgtmgen.org/06b54bb0-4544-47e0-9951-1b83b2f6e8dd)

2023-07-14 17:14 UTC, YumNumm commented
既存の値から変更した点をメモさせていただきました!
自分からデザイナーのゆめゆめさんに デザイン周りでいくつか確認したい点があったので 合わせて確認取ろうと思います
一応マージ 確認後でもよろしいでしょうか?

2023-07-14 17:18 UTC, daiki1003 commented on lib/features/hero/ui/hero_section_mobile.dart
> +        Spaces.vertical_24,
すみません、これは意図的ではないので直します！

2023-07-14 17:18 UTC, daiki1003 commented
> 一応マージ 確認後でもよろしいでしょうか?

デザイナー確認後にマージということでしょうか！

2023-07-14 17:27 UTC, YumNumm commented
すみません! 少し日本語が誤解を生む表現でした! 
デザイナーさんに確認後、マージをしたいので 待機にしたい という意です!
なので、朝日さんの解釈で合っております🙏

2023-07-14 17:36 UTC, YumNumm requested changes
一度Approveした後の変更依頼申し訳ございません! 
1点コメントさせていただきましたので、ご確認よろしくお願いします🙇

2023-07-14 17:36 UTC, YumNumm commented on lib/core/theme/dimension.dart
> +  static const SizedBox horizontal_40 = SizedBox(width: 40);
![must-badge](https://img.shields.io/badge/review-must-red.svg)
こちら、`SizedBox(height: xx)`かと思われます!!

2023-07-14 17:37 UTC, YumNumm commented on lib/core/theme/dimension.dart
> +  static const SizedBox horizontal_40 = SizedBox(width: 40);
上下方向に押しつぶされたような形になってしまっておりました...!
![image](https://github.com/FlutterKaigi/2023/assets/73390859/b99a8d8b-4917-4c28-b69f-1432e22e8059)

2023-07-14 17:40 UTC, daiki1003 commented on lib/core/theme/dimension.dart
> +  static const SizedBox horizontal_40 = SizedBox(width: 40);
いやー、酷すぎる...
直しました 🙏

2023-07-15 06:35 UTC, daiki1003 commented
@YumNumm 
https://flutterkaigi.slack.com/archives/C05HTMSQXPA/p1689398551432969?thread_ts=1689358516.458599&cid=C05HTMSQXPA
の流れを汲み、元の通りのに変更をしています！

2023-07-15 13:10 UTC, YumNumm approved these changes

2023-07-15 13:10 UTC, YumNumm commented
@daiki1003 ありがとうございます! 問題なさそうです! 
お手すきの際にマージよろしくお願いします!

2023-07-17 17:35 UTC, merged