Feature/improve scroll
FlutterKaigi/2023 pull request #120
Opened 2023-07-24 16:55 UTC by tomohiko-tanihata

## Issue

- close #93 
## Overview (Required)

- `SingleChildScrollView` を `CustomScrollView` に変更
- `StaffTable` には `SliverGrid` を使用

環境が用意できていないためモバイル端末では試せてはいないですが理論上は動作軽くなるはずです！
PC Chrome環境で24名のダミーデータに対し試したところ、目で見て分かるくらいにはスクロールが改善されたことは確認できています。

### before
https://github.com/FlutterKaigi/2023/assets/32211772/d157a5f7-8cf3-41f5-a754-77c7d3bbd73d

### after

https://github.com/FlutterKaigi/2023/assets/32211772/7de9bc7e-c280-4ee6-8030-f3222df5e578

## Screenshot
- `CustomScrollView` を使った場合は総スクロール量が取得できないため背景は固定化しています
  - 今回のケースだと `scrollController.position.minScrollExtent/maxScrollExtent`を使えば `CustomScrollView` の場合でも総スクロール量が取得できるかもしれません。
- `SliverGrid` を使用する都合上、並び順が左詰めになっています。これにより `StaffTable` の最終行だけ差分が発生します。

|           Before           |           After            |
|:--------------------------:|:--------------------------:|
| <img src="https://github.com/FlutterKaigi/2023/assets/32211772/fe090589-1b28-4235-9861-768429d06402" width="300" /> | <img src="https://github.com/FlutterKaigi/2023/assets/32211772/41ab4434-fb55-41f8-836d-5c9931f3177c" width="300" /> |

2023-07-26 18:46 UTC, YumNumm requested changes
レビュー遅くなり申し訳ございません! 
いくつかコメントさせていただきました! 

---

レビューに際して Release Buildしたものを
https://flutterkaigi-improve-scroll.pages.dev/
にアップロードしました。
マージ後に消去します

2023-07-26 18:46 UTC, YumNumm commented on lib/app/home_page.dart
> +      horizontal: horizontal as double,
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
型キャストをするよりも、`.toDouble()`の方が適切かもしれません

```suggestion
      horizontal: horizontal.toDouble(),
```

2023-07-26 18:46 UTC, YumNumm commented on lib/features/staff/ui/staff_table.dart
> +    const snsIconHeight = 40;
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

横幅が狭くなった時の SNSアイコンの高さ計算が うまく行っていなさそうです。
具体的には、SNSリストが`Wrap`により改行された時にoverflowするようになってしまっていそうです
![image](https://github.com/FlutterKaigi/2023/assets/73390859/c4d86b5b-0d62-4a2f-8413-f949c573c479)

```suggestion
    final snsIconHeight = 32 * ((width - cardMargin * 2) / staff.sns.length);
```

2023-07-26 23:39 UTC, tomohiko-tanihata commented on lib/app/home_page.dart
> +      horizontal: horizontal as double,
`toDouble()`を都度付与するの面倒だったので`horizontal`をdouble型に修正しました！
```
final horizontal = max<double>(16, (width - largeScreenSize) / 4.0);
```

2023-07-26 23:54 UTC, tomohiko-tanihata commented on lib/features/staff/ui/staff_table.dart
> +    const snsIconHeight = 40;
SNSアイコン一覧が2行になることを考慮していないためレイアウト崩れが生じるのはご指摘の通りです。
そもそも2行になること自体がバグという認識で https://github.com/FlutterKaigi/2023/pull/107 のPRで改善される予定と思っています！2行になるバグ修正がマージされてからこちらのPRをマージしていただければと思います！！！

若干話が逸れるのですが、改めてアイコン一覧をWidget Inspectorで見ていて下記の振る舞いを確認しました。
- `SnsIcon`の`size = 32`を指定しているにも関わらず`height`が40になっていること
  - `SvgPicture`の内部実装が怪しいですが詳細は追えてないです
- アイコンは元のsvgのアスペクト比を保持して表示されており、横幅指定が効いていないこと
  - noteのアイコンは33:32で表示されています
  - `SvgPicture`の仕様が`height`が指定されていると`width`に関係なくアスペクト比を保持して表示するとなっていました。

特に後者をケアしようと思うと若干手を加えないといけなさそうなので、2行になるバグ修正を待ちたいと思ってます！！

2023-07-26 23:57 UTC, tomohiko-tanihata commented
@YumNumm 
レビューありがとうございます！リリースビルドされたもの確認しました！パフォーマンス改善されていることが確認できて良かったです🎉

2023-07-28 11:38 UTC, YumNumm commented on lib/features/staff/ui/staff_table.dart
> +    const snsIconHeight = 40;
承知しました! ありがとうございます!

2023-07-28 11:39 UTC, YumNumm approved these changes
LGTMです! ご対応ありがとうございました!
マージよろしくお願いします!

2023-07-29 14:37 UTC, YumNumm commented
@tomohiko-tanihata 
一度mainにマージ後に別のPRでレイアウトの修正を行おうと思います!

2023-07-29 14:37 UTC, merged