スポンサー関連のデータを追加
FlutterKaigi/2023 pull request #176
Opened 2023-09-24 14:16 UTC by tatsutakein

## Issue

- [スポンサーセクション（第2段階）の設計・実装 · Issue #164 · FlutterKaigi/TasksBoard](https://github.com/FlutterKaigi/TasksBoard/issues/164)

## Overview (Required)

スポンサー関連のデータを追加します。

## Links

- 

## Screenshot

|           Before           |           After            |
|:--------------------------:|:--------------------------:|
| <img src="" width="300" /> | <img src="" width="300" /> |

2023-09-24 14:37 UTC, YumNumm requested changes
@tatsutakein 
2点 コメントさせて頂きました🙏 ご確認お願い致します!

2023-09-24 14:37 UTC, YumNumm commented on lib/features/sponsor/data/sponsor_data_source.dart
> +  }
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
こちら、`Future<List<Sponsor>>`ではなく`List<Sponsor>`の方が良さそうですが、`FutureProvider`にしている意図ありますでしょうか?

---

![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
もし同期関数で良いのであれば、`Provider`の方が扱いやすいかもしれません!
```dart
@Riverpod(keepAlive: true)
List<Sponsor> sponsor(...) => [...];
```

2023-09-24 14:37 UTC, YumNumm commented on lib/features/sponsor/data/sponsor_data_source.dart
> +        '10Xではモバイル・WebアプリでFlutterを、サーバーサイドではDartを利用しています。このように10XはFlutter・Dartに支えられており、今後も価値あるプロダクトを作り続ける上で重要な技術への支援・還元を行っていきます。',
> GitHub Actions/analyze
> 
> The line length exceeds the 80-character limit.
> 
> Try breaking the line across multiple lines.
> See https://dart.dev/lints/lines_longer_than_80_chars to learn more about this problem.

80文字制限について、ファイル全体でignoreしてしまって良さそうです!

https://github.com/FlutterKaigi/2023/actions/runs/6290584624?pr=176#:~:text=by%20humans.txt-,Annotations,-4%20warnings%20and

2023-09-25 00:19 UTC, tatsutakein commented on lib/features/sponsor/data/sponsor_data_source.dart
> +  }
仰るとおり、同期関数のため普通に `List<Sponsor>` で良さそうでした！
e5b026c2629d4d8a3f62f53d593e6270ec26834e にて対応いたしました。

2023-09-25 00:20 UTC, tatsutakein commented on lib/features/sponsor/data/sponsor_data_source.dart
> +        '10Xではモバイル・WebアプリでFlutterを、サーバーサイドではDartを利用しています。このように10XはFlutter・Dartに支えられており、今後も価値あるプロダクトを作り続ける上で重要な技術への支援・還元を行っていきます。',
おお、ありがとうございます…！
960b07fe845e23b23467f23cbaa5acfe20c08ba4 にて対応いたしました。

2023-09-25 00:21 UTC, tatsutakein commented
@YumNumm 
いただいたフィードバックについて対応いたしました。
お手数ですが、再度ご確認いただけますでしょうか 🙏

2023-09-25 11:17 UTC, blendthink approved these changes

2023-09-25 11:21 UTC, merged