Session内にYoutubeを載せる実装を行いました
FlutterKaigi/2023 pull request #220
Opened 2023-12-08 03:19 UTC by iseruuuuu

## Issue

- close #ISSUE_NUMBER

## Overview (Required)

- 

## Links

- 

## Screenshot

|           Before           |           After            |
|:--------------------------:|:--------------------------:|
| <img src="" width="300" /> | <img src="" width="300" /> |

2023-12-08 03:44 UTC, tatsutakein requested changes
@iseruuuuu 
ご対応いただきありがとうございます！
コメント入れましたので、ご確認いただけますと幸いです 🙏

2023-12-08 03:44 UTC, tatsutakein commented on lib/features/session/ui/detail/youtube_url_mixin.dart
> +  String getUrl(String user) {
<!-- 細かい指摘 -->
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

細かいですが `user` ではなさそうな気がしました 👀

```suggestion
  String getUrl(String title) {
```

2023-12-08 03:44 UTC, tatsutakein commented on lib/features/session/ui/detail/youtube_url_mixin.dart
<!-- こういう表現もあります -->
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

タイトルを元に変換するのではなく、セッションのメンバーとして持たせてしまったほうがデータの構造として綺麗な気がしました💡
少し労力掛かると思うので、あくまで参考程度で無視していただいても大丈夫です 🙆

https://github.com/FlutterKaigi/2023/blob/8e909538ac84387b82c1a718cdacf1ffec881b04/lib/features/session/data/session.dart#L11-L22

2023-12-08 03:58 UTC, blendthink commented on lib/features/session/ui/detail/youtube_url_mixin.dart
> +  String getUrl(String user) {
@iseruuuuu 
![imo-badge](https://img.shields.io/badge/review-imo-skyblue.svg) 
`Session` には `uuid` というフィールドがあるので、それをつかった `Map<String, String>` データを作成しておいて、その `Map<String, String>` データを元に変換するような `extension` を作成するとより一般的な実装で良いかなと思いました！
（ `title` で判定しようとするとスペースや文字が半角かどうかを確認しないといけなくなり、確認が大変になってしまいそう ）

2023-12-08 04:03 UTC, blendthink commented on lib/features/session/ui/detail/session_detail.dart
> +        youtubeGap: MediaQuery.of(context).size.width / 1.5,
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
今後は `MediaQuery.sizeOf` を使っていきましょ 💪 
https://api.flutter.dev/flutter/widgets/MediaQuery/sizeOf.html
```suggestion
        youtubeGap: MediaQuery.sizeOf(context).width / 1.5,
```

2023-12-08 05:07 UTC, daiki1003 commented on lib/features/session/ui/detail/session_detail_content.dart
> +          controller: YoutubePlayerController.fromVideoId(
![badge](https://img.shields.io/badge/review-must-red.svg)
![badge](https://img.shields.io/badge/review-ask-green.svg)
ちゃんと `dispose` されますでしょうか？

2023-12-08 05:12 UTC, daiki1003 commented on lib/features/session/ui/detail/youtube_url_mixin.dart
そうですね、それか `calculated property` としてしまっても綺麗かもですね！

```dart
sealed class Session with _$Session {
  const factory Session({
    ...
  }) = _Session ;

  Session._();

  late final String youtubeUrl = switch (title /* uuid とかの方が良い気はする？ */) {
     'Flutter アプリにおけるテスト戦略の見直しと自動テストの導入' => 'VHhZlTDfwIQ';
     '詳解！Flutterにおける課金実装' => 'NcfrY-EN8Pg';
  };
}
```

と言うイメージです。

2023-12-08 05:14 UTC, daiki1003 commented on lib/features/session/ui/detail/youtube_url_mixin.dart
ただ、 `Session` と言うドメインは `youtube` のことを知らない方が良い気はするので、`extension` とかでも良いのかも？

```dart
// session_youtube_url_ex.dart
class SessionYoutubeUrlEx on Session {
  late final String youtubeUrl = switch (title /* uuid とかの方が良い気はする？ */) {
     'Flutter アプリにおけるテスト戦略の見直しと自動テストの導入' => 'VHhZlTDfwIQ';
     '詳解！Flutterにおける課金実装' => 'NcfrY-EN8Pg';
     ...
  };
}
```

2023-12-08 05:14 UTC, daiki1003 commented on lib/features/session/ui/detail/youtube_url_mixin.dart
そして、このプロパティが欲しい箇所でだけimportすると

2023-12-08 05:15 UTC, daiki1003 commented on lib/features/session/ui/detail/youtube_url_mixin.dart
https://github.com/FlutterKaigi/2023/pull/220/files#r1419902017
に似た様なコメントがあったｗ

2023-12-13 01:06 UTC, iseruuuuu commented on lib/features/session/ui/detail/session_detail_content.dart
> +        width: youtubeGap,
[ef3a503](https://github.com/FlutterKaigi/2023/pull/220/commits/ef3a503ea1032cec4cebad9a11c3e652ab3b7589)
こちらで修正しました！

2023-12-13 01:08 UTC, iseruuuuu commented on lib/features/session/ui/detail/session_detail.dart
> +        youtubeGap: MediaQuery.of(context).size.width / 1.5,
教えていただきありがとうございます！（ MediaQuery.of(context).size.widthで覚えてしまっていたので、覚えなさないとと思いました💦）
こちらで修正しました！
[86e7815](https://github.com/FlutterKaigi/2023/pull/220/commits/86e781579beadc001b59c38c30425caff31bf184)

2023-12-13 01:46 UTC, iseruuuuu commented on lib/features/session/ui/detail/youtube_url_mixin.dart
教えていただいた実装を参考にして、修正してみました🙇
[daa9daf](https://github.com/FlutterKaigi/2023/pull/220/commits/daa9daf3583825494c3092f48cb52b58ed519cd2)

（一応、間違えていないかビルドして、それぞれのSessionを確認したところ、正しい動画になっていることが確認できました！）

2023-12-13 02:32 UTC, iseruuuuu commented on lib/features/session/ui/detail/session_detail_content.dart
> +          controller: YoutubePlayerController.fromVideoId(
教えていただきありがとうございます！ちゃんとできていなかったのでこちらで修正してみました。
[a1c58b6](https://github.com/FlutterKaigi/2023/pull/220/commits/a1c58b63e586b1194db1c61d286822d4f1dbe88e)

2023-12-13 02:34 UTC, iseruuuuu commented
@tatsutakein @blendthink @daiki1003 
レビューいただきありがとうございます！！！
いただけたコメントを参考にし、修正してみました！お手隙の際にご確認いただけると幸いです🙇

2023-12-18 00:17 UTC, blendthink commented on lib/features/session/data/youtube_provider.dart
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
@iseruuuuu 
`Controller` の `close()` が呼ばれていないため、意図しない挙動になってしまうことがありそうです。
（現状は問題なさそう）

`ref.onDispose()` で `close()` を呼び出すようにするか、公式ドキュメントの example のように `StatefulWidget` の `dispose()` で `close()` を呼び出すようにした方が良さそうです。

ちなみに `Controller` を `Riverpod` の `Provider` で管理するとライフサイクルの管理が複雑になってしまうため、個人的にはあまりおすすめはしません。

FYI:
- https://riverpod.dev/docs/concepts/modifiers/auto_dispose#example-canceling-http-requests-when-no-longer-used
- https://pub.dev/packages/youtube_player_iframe/example

2023-12-18 00:53 UTC, iseruuuuu commented on lib/features/session/data/youtube_provider.dart
コメントいただきありがとうございます〜！！

Controller の close() が呼ばれていないため、意図しない挙動になってしまうことがありそうである点は全く気づけなかったので、PRの中で修正ができてよかったです！

サンプルコードを見ながら`close()`の処理を書いてみたのですが、close()がFuture<void>だったので、disposeをFuture<void>する実装をしてみました。

こちらで修正してみました！
[09169a4](https://github.com/FlutterKaigi/2023/pull/220/commits/09169a45f54daa1d8cb36b1b77a56201da4fca84)

2023-12-18 01:06 UTC, blendthink approved these changes
LGTM です！
ご対応ありがとうございます！
![LGTM](https://image.lgtmoon.dev/231392)

2023-12-18 01:41 UTC, daiki1003 commented on lib/features/session/data/session.dart
> +class Session with _$Session {
![badge](https://img.shields.io/badge/review-must-red.svg)
![badge](https://img.shields.io/badge/review-ask-green.svg)
3行になっていることって意図的でしょうか？ 👀

2023-12-18 01:42 UTC, daiki1003 commented on lib/features/session/data/session.dart
> +    return switch (uuid) {
![badge](https://img.shields.io/badge/review-nits-blue.svg)
```dart
String get youtubeUrl => return switch {
  ...
};
```
の方がインデントが1段下がったりしますがお好みで笑

2023-12-18 01:44 UTC, daiki1003 commented on lib/features/session/data/session.dart
> +extension SessionYoutubeUrlEx on TalkSession {
![badge](https://img.shields.io/badge/review-imo-orange.svg)
`YoutubeUrl` って `Session` モデルを欲しているクラスで必ずしも欲しい情報ではない (二次的な情報？)ので、 `session_youtube_ex.dart` とファイルを切り出しても良さそうですね。
必要なクラスのみ↑をimportするという。

2023-12-18 01:45 UTC, daiki1003 commented on lib/features/session/ui/detail/session_detail_content.dart
> +class SessionDetailContent extends StatefulWidget {
![badge](https://img.shields.io/badge/review-imo-orange.svg)
`StatefulWidget` にするより、 `HookWidget` にして、`useYoutubePlayerController` の様なHookを定義できると、 `dispose` も気にせずに書けるので良さそうですね！

2023-12-18 01:47 UTC, daiki1003 requested changes
一個だけmustの部分が気になっております！

2023-12-18 03:36 UTC, iseruuuuu commented on lib/features/session/data/session.dart
> +class Session with _$Session {
教えていただきありがとうございます！
ミスでした🙇　Android Studioで自動整形をしたところ上のような内容になってしまったと思われます。
こちらで修正します！
[a8fa189](https://github.com/FlutterKaigi/2023/pull/220/commits/a8fa189870cfd94412abaf340aba60842ef58809)

2023-12-18 03:36 UTC, tatsutakein approved these changes
朝日さんが must コメントしているところ以外は良きと思いました！
LGTM です 👍

2023-12-18 03:39 UTC, iseruuuuu commented on lib/features/session/data/session.dart
> +    return switch (uuid) {
とてもいい修正だと思いました！なので修正させていただきました！教えていただきありがとうございます😄
[470bf49](https://github.com/FlutterKaigi/2023/pull/220/commits/470bf4971de4ad2989b6ea728f75442d806d1d90)

2023-12-18 03:47 UTC, iseruuuuu commented on lib/features/session/data/session.dart
> +      '21abbd32-6864-487a-8066-c9d7f7e5e9be' => 'cMS2FzbhXJ8',
とても賛成できます！こちらで修正してみました（タイトルをコメントすることにしました！）
[fa9efa0](https://github.com/FlutterKaigi/2023/pull/220/commits/fa9efa021782f449e722b39a04968560c630f342)

2023-12-18 03:58 UTC, iseruuuuu commented on lib/features/session/data/session.dart
> +extension SessionYoutubeUrlEx on TalkSession {
他の実装を見る感じだと、Session.dart内でまとめているのかなという印象を受けて統一して実装してみました。例えば、
```
extension TalkSessionIsSponsored on TalkSession {
  bool get isSponsored {
    return tags.any((tag) => tag.name == 'Sponsored');
  }
}
```

この辺りの実装もSession モデルを欲しているクラスで必ずしも欲しい情報ではないと思いましたがSession.dart内で記載があったため、合わせる方でやりました！（意図が間違っていたらすみません🙇）

2023-12-18 04:21 UTC, iseruuuuu commented on lib/features/session/ui/detail/session_detail_content.dart
> +class SessionDetailContent extends StatefulWidget {
こちらで修正してみました！（間違っていたりしましたら教えていただけると幸いです🙇）
[c3f7c13](https://github.com/FlutterKaigi/2023/pull/220/commits/c3f7c139440ac62e3a91e48baf5bd106a3137edd)

2023-12-20 00:05 UTC, daiki1003 approved these changes
LGTM!

ありがとうございました！

2023-12-20 00:18 UTC, iseruuuuu commented
レビューいただきありがとうございます！！マージさせていただきます！！

2023-12-20 00:18 UTC, merged